// All copy for leen.fit, one object per language.
// Voice rules (from docs/PRODUCT.md + RELEASE_PLAN.md in the app repo):
// soft, never guilt; "companion", never "nutritionist"; numbers are honest
// estimates; no pricing, no "unlimited", no medical claims.
// Nutrition figures come from the app's NutritionDB.swift so the demos
// show exactly what Leen would log.

export const site = {
  origin: 'https://leen.fit',
  // Paste the App Store link here at launch — every CTA switches from
  // "Coming soon" to a real download button.
  appStoreUrl: '',
  // Optional public TestFlight link; shows a "Join the beta" button when set.
  testflightUrl: '',
  contactEmail: 'tan.acute@gmail.com',
  company: 'Masna',
  year: 2026,
  updated: '2026-10-04',
};

// Food tiles reuse the app's ProceduralFoodArt backdrop palettes.
// name/alt = the label in this language and the other one.
const foods = {
  kabsa:   { emoji: '🍛', pal: 'honey', kcal: 650, en: 'Kabsa', ar: 'كبسة', perEn: '1 plate, chicken + rice', perAr: 'صحن واحد، دجاج ورز' },
  mandi:   { emoji: '🍖', pal: 'sand', kcal: 680, en: 'Mandi', ar: 'مندي' },
  karak:   { emoji: '🍵', pal: 'terracotta', kcal: 70, en: 'Karak', ar: 'كرك' },
  milkTea: { emoji: '🍵', pal: 'terracotta', kcal: 70, en: 'Milk Tea', ar: 'شاي بالحليب', perEn: '1 cup, no sugar', perAr: 'كوب واحد، بدون سكر' },
  spanish: { emoji: '☕', pal: 'sand', kcal: 270, en: 'Spanish Latte', ar: 'سبانش لاتيه', perEn: '16 oz iced', perAr: '١٦ أونصة، مثلج' },
  shawarma:{ emoji: '🌯', pal: 'terracotta', kcal: 500, en: 'Shawarma', ar: 'شاورما' },
  hummus:  { emoji: '🫓', pal: 'sage', kcal: 270, en: 'Hummus & Pita', ar: 'حمص وخبز' },
  dates:   { emoji: '🌴', pal: 'honey', kcal: 133, en: 'Dates', ar: 'تمر' },
  gahwa:   { emoji: '☕', pal: 'stone', kcal: 10, en: 'Arabic Coffee', ar: 'قهوة عربية' },
  matcha:  { emoji: '🍵', pal: 'sage', kcal: 200, en: 'Matcha Latte', ar: 'ماتشا لاتيه' },
  eggs:    { emoji: '🍳', pal: 'stone', kcal: 182, en: 'Scrambled Eggs', ar: 'بيض مخفوق', perEn: '2 large eggs', perAr: 'بيضتان كبيرتان' },
  toast:   { emoji: '🍞', pal: 'sage', kcal: 116, en: 'Buttered Toast', ar: 'توست بالزبدة', perEn: '1 slice with butter', perAr: 'شريحة واحدة مع الزبدة' },
  banana:  { emoji: '🍌', pal: 'blush', kcal: 105, en: 'Banana', ar: 'موز' },
  biryani: { emoji: '🍛', pal: 'honey', kcal: 560, en: 'Biryani', ar: 'برياني' },
  saleeg:  { emoji: '🍚', pal: 'stone', kcal: 560, en: 'Saleeg', ar: 'سليق' },
  jareesh: { emoji: '🥣', pal: 'sand', kcal: 380, en: 'Jareesh', ar: 'جريش' },
  mutabbaq:{ emoji: '🥟', pal: 'honey', kcal: 450, en: 'Mutabbaq', ar: 'مطبق' },
  mansaf:  { emoji: '🍖', pal: 'blush', kcal: 750, en: 'Mansaf', ar: 'منسف' },
  koshari: { emoji: '🍝', pal: 'terracotta', kcal: 640, en: 'Koshari', ar: 'كشري' },
  sambousa:{ emoji: '🥟', pal: 'sand', kcal: 290, en: 'Sambousa', ar: 'سمبوسة' },
  falafel: { emoji: '🌯', pal: 'sage', kcal: 480, en: 'Falafel Wrap', ar: 'فلافل' },
  kunafa:  { emoji: '🍮', pal: 'honey', kcal: 420, en: 'Kunafa', ar: 'كنافة' },
  luqaimat:{ emoji: '🍡', pal: 'blush', kcal: 340, en: 'Luqaimat', ar: 'لقيمات' },
  shakshuka:{ emoji: '🍳', pal: 'terracotta', kcal: 300, en: 'Shakshuka', ar: 'شكشوكة' },
  saffron: { emoji: '☕', pal: 'honey', kcal: 190, en: 'Saffron Latte', ar: 'لاتيه زعفران' },
};
export { foods };

const marqueeA = ['kabsa', 'karak', 'mandi', 'spanish', 'shawarma', 'dates', 'mutabbaq', 'gahwa', 'kunafa', 'hummus', 'saleeg', 'matcha'];
const marqueeB = ['luqaimat', 'biryani', 'shakshuka', 'jareesh', 'saffron', 'falafel', 'mansaf', 'sambousa', 'koshari', 'eggs', 'toast', 'banana'];

// Hero demo: three scenes with a running daily total (goal 2,200).
const scene = (key, servings) => ({ key, servings });

export const content = {
  en: {
    lang: 'en',
    dir: 'ltr',
    path: '/',
    other: { lang: 'ar', label: 'العربية', path: '/ar/' },
    meta: {
      title: 'Leen — The food journal that understands how you eat',
      description: 'Log meals by typing, speaking or snapping a photo — in English, Arabic, or both. Leen turns what you eat into a beautiful, private journal. Coming soon to iPhone.',
      ogImage: '/og-en.png',
      ogLocale: 'en_US',
    },
    brand: 'leen',
    skip: 'Skip to content',
    nav: { how: 'How it works', ledger: 'The Ledger', privacy: 'Privacy', faq: 'FAQ', home: 'Leen home', menu: 'Menu', primary: 'Primary', footer: 'Footer' },
    cta: {
      soon: 'Coming soon',
      soonLong: 'Coming soon to the App Store',
      download: 'Download on the App Store',
      beta: 'Join the beta',
    },
    hero: {
      eyebrow: 'A food journal for iPhone',
      title: 'Your meals,<br><em>beautifully understood.</em>',
      lede: 'Tell Leen what you ate — in English, Arabic, or the mix you actually speak — and it becomes a beautiful page in your journal. No forms. No searching. No judgment.',
      secondary: 'See how it works',
      notes: ['No account', 'Works offline', 'English & العربية'],
      demoLabel: 'Leen app demo: a meal typed in one sentence becomes a saved, itemised card.',
    },
    app: {
      today: 'Today',
      of: 'of',
      kcal: 'kcal',
      left: 'left',
      goal: 2200,
      placeholder: 'What did you eat?',
      photo: 'Photo',
      speak: 'Speak',
      saved: 'Saved',
      undo: 'Undo',
      edit: 'Edit',
      perServing: 'Per serving:',
      servings: (n) => (n === 1 ? '1 serving' : `${n} servings`),
      greeting: 'Tell me one thing you ate today — any words work (“karak and toast”, “chicken kabsa”) and I’ll do the rest.',
      scenes: [
        { text: '2 eggs and toast', items: [scene('eggs', 2), scene('toast', 1)],
          reply: 'Got it. 2× Scrambled Eggs + Buttered Toast — 480 kcal, noted. That puts you at 480 — 1,720 still in the tank.' },
        { text: 'chicken kabsa and a karak', items: [scene('kabsa', 1), scene('milkTea', 1)],
          reply: 'Kabsa and karak — 720 kcal, noted. You’re at 1,200 today, 1,000 still in the tank.' },
        { text: 'spanish latte', items: [scene('spanish', 1)],
          reply: 'Spanish latte? 270 kcal and about 150 mg of caffeine. Not judging.' },
      ],
    },
    ways: {
      kicker: 'How it works',
      title: 'One sentence is<br><em>a whole entry.</em>',
      lede: 'Log the way you’d tell a friend. Leen works out the portions, the numbers and the tidy page.',
      type: { title: 'Type it', body: '“2 eggs and toast.” That’s it — itemised, counted and saved in a second.', demo: 'chicken kabsa and a karak' },
      say: { title: 'Say it', body: 'Hold the mic and talk. Your words appear in the composer before anything is sent.', demo: ['two', 'eggs', 'and', 'toast'], listening: 'Listening…' },
      snap: { title: 'Snap it', body: 'Send a photo of your plate and Leen reads what’s on it.', fine: 'Photo understanding uses optional cloud processing — only with your permission.', reading: 'Reading your plate…' },
    },
    food: {
      kicker: 'It knows your food',
      title: 'Kabsa at home. Karak at midnight.<br><em>Leen already knows.</em>',
      lede: 'Leen comes with the dishes, café drinks and restaurant menus of the region — and understands English, Arabic, or both in the same sentence.',
      marqueeA, marqueeB,
      mixed: { text: 'كبسة دجاج and a karak', caption: 'Mix languages freely. Leen keeps up.', items: ['kabsa', 'milkTea'] },
    },
    correct: {
      kicker: 'Honest by design',
      title: 'Correct it the way<br><em>you’d say it.</em>',
      lede: '“Make that two.” “I didn’t eat the fries.” Corrections are just conversation — and Undo is always one tap away.',
      fix: 'make that two',
      reply: 'Done — two slices now.',
      honestTitle: 'Honest numbers',
      honestBody: 'When a number is an estimate, Leen says so — ~650 — and adjusting the serving is one tap away. No fake precision, ever.',
      estimate: 'Estimate · tap to adjust',
    },
    ledger: {
      kicker: 'The Ledger',
      title: 'Your food diary,<br><em>as a magazine.</em>',
      lede: 'Pinch out and every meal becomes a page — each plate set in Leen’s warm studio style, day by day, week by week.',
      points: ['Your week at a glance', 'Search any food, meal or day', 'Share any card as a designed image'],
      mock: {
        title: 'The Ledger',
        search: 'Food, meal type, or date',
        stats: '5 days · 16 plates',
        week: 'Your week',
        days: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
        summary: '5 days logged · 11 different foods',
        top: [{ key: 'karak', times: '3 times' }, { key: 'kabsa', times: '2 times' }, { key: 'dates', times: '2 times' }],
        today: 'Today',
        todayKcal: '1,035 kcal',
        plates: [
          { key: 'eggs', meal: 'Breakfast' }, { key: 'karak', meal: 'Breakfast' },
          { key: 'kabsa', meal: 'Lunch' }, { key: 'dates', meal: 'Snack' },
        ],
        yesterday: 'Yesterday',
        yesterdayKcal: '1,670 kcal',
        plates2: [{ key: 'shakshuka', meal: 'Breakfast' }, { key: 'spanish', meal: 'Snack' }, { key: 'mandi', meal: 'Dinner' }, { key: 'kunafa', meal: 'Dessert' }],
      },
    },
    gentle: {
      kicker: 'A gentler way',
      title: 'Numbers, only if<br><em>you want them.</em>',
      lede: 'Say “hide calories” and the numbers step off the page — your journal keeps going in food and protein instead of arithmetic. Say “show calories” and they return.',
      hide: 'Hide calories',
      show: 'Show calories',
      try: 'Tap to try it',
      promise: 'Leen never judges, never scolds, never turns red.',
      day: 'Thursday',
      rows: [
        { key: 'karak', meal: 'Morning', protein: '3 g protein' },
        { key: 'kabsa', meal: 'Lunch', protein: '38 g protein' },
        { key: 'dates', meal: 'Afternoon', protein: '1 g protein' },
      ],
      totalKcal: '853 kcal',
      totalGentle: '3 plates · 42 g protein',
    },
    smart: {
      kicker: 'Quietly smart',
      title: 'The details,<br><em>taken care of.</em>',
      items: [
        { icon: 'ask', title: 'Ask your journal', body: '“How much caffeine today?” Answers arrive with receipts — the meals behind every number.', q: 'How much caffeine today?', a: '240 mg — karak, a Spanish latte and Arabic coffee.' },
        { icon: 'drop', title: 'Beyond calories', body: 'Caffeine in milligrams. Sugar, sodium and fibre from real labels. Protein, carbs and fat on every card.' },
        { icon: 'repeat', title: 'Your usuals', body: 'Saved meals come back in a tap — your regular breakfast is one line, not a search.' },
        { icon: 'week', title: 'A weekly recap', body: 'A visual look back at your week that reads like a note from a friend, not a report card.' },
        { icon: 'heart', title: 'Apple Health', body: 'Meals flow into Apple Health, and the activity you earn shows up in your day.' },
        { icon: 'widget', title: 'Widgets', body: 'Today’s journal on your Home Screen, dressed in the same theme as the app.' },
      ],
    },
    themes: {
      title: 'Make it yours.',
      lede: 'Four journal themes, each with a matching app icon. Try one — this page will follow.',
      names: { matcha: 'Matcha', lilac: 'Lilac', peach: 'Peach', ocean: 'Ocean' },
      label: 'Choose a theme',
    },
    privacy: {
      kicker: 'Private by design',
      title: 'Your journal lives<br><em>on your iPhone.</em>',
      points: [
        { title: 'No account. No sign-up.', body: 'Open the app and start. Leen never asks for your name, email or phone number.' },
        { title: 'On-device by default', body: 'On supported iPhones, Apple’s on-device model understands your meals. Your words stay on the phone.' },
        { title: 'Works offline', body: 'Your journal and Leen’s built-in food knowledge work without a connection.' },
        { title: 'Cloud is your choice', body: 'Want cloud-powered understanding? Leen asks first, explains what’s sent, and you can switch back any time.' },
        { title: 'No ads. No trackers.', body: 'No advertising or analytics SDKs. Your meals are yours.' },
      ],
      link: 'Read the privacy policy',
    },
    story: {
      kicker: 'Why “Leen”',
      title: 'From لين —<br><em>softness.</em>',
      body: 'The mark fuses a Latin L with the Arabic ل. The name means softness: a journal with no guilt and no lectures — just a calm, beautiful record of how you eat, in the language you think in.',
      alt: 'The Leen mark: a calligraphic letter that reads as both L and ل',
    },
    faq: {
      kicker: 'FAQ',
      title: 'Questions,<br><em>answered.</em>',
      items: [
        { q: 'When can I get Leen?', a: 'Leen is in beta now and coming soon to the App Store for iPhone.' },
        { q: 'Is Leen free?', a: 'Yes — journaling with Leen is free. An optional Leen Pro subscription adds cloud-powered understanding; what it includes is shown clearly in the app before you subscribe.' },
        { q: 'Do I need an account?', a: 'No. There’s no sign-up and no login. Your journal is stored on your iPhone, with optional backup to your own iCloud.' },
        { q: 'Does it really understand Arabic?', a: 'Yes. Leen is fully available in Arabic and English, and you can log in either language — or both in one sentence.' },
        { q: 'Which iPhones are supported?', a: 'Leen runs on iPhones with iOS 18.1 or later. On iPhones with Apple Intelligence, Leen uses Apple’s on-device model for richer understanding; elsewhere, its built-in food matching does the work.' },
        { q: 'Is Leen medical or dietary advice?', a: 'No. Leen is a journal, not medical advice. Numbers are estimates, and Leen tells you when they are. For medical nutrition questions, please talk to a professional.' },
      ],
    },
    final: {
      title: 'The page is still<br><em>blank today.</em>',
      lede: 'Leen is coming soon to the App Store. Your first entry takes one sentence.',
      ledeLive: 'Your first entry takes one sentence.',
    },
    footer: {
      tagline: 'Your meals, beautifully understood.',
      privacy: 'Privacy',
      terms: 'Terms',
      contact: 'Contact',
      legal: 'Leen is a journal, not medical advice.',
      trademarks: 'Apple, iPhone, Apple Health, Apple Intelligence, iCloud and App Store are trademarks of Apple Inc.',
      madeIn: 'Made with care for kabsa, karak and everything in between.',
    },
    notFound: {
      title: 'This page isn’t in the journal.',
      body: 'The link may be old, or the page moved. Let’s get you back to the start.',
      home: 'Back to Leen',
    },
    legalNav: { back: 'Back to Leen', updated: 'Last updated' },
  },

  ar: {
    lang: 'ar',
    dir: 'rtl',
    path: '/ar/',
    other: { lang: 'en', label: 'English', path: '/' },
    meta: {
      title: 'لين — يوميات طعام تفهم أكلك',
      description: 'سجّل وجباتك بالكتابة أو الصوت أو الصورة — بالعربي أو الإنجليزي أو الاثنين معًا. لين يحوّل أكلك إلى دفتر جميل وخاص بك. قريبًا على الآيفون.',
      ogImage: '/og-ar.png',
      ogLocale: 'ar_SA',
    },
    brand: 'لين',
    skip: 'انتقل إلى المحتوى',
    nav: { how: 'طريقة الاستخدام', ledger: 'الدفتر', privacy: 'الخصوصية', faq: 'الأسئلة', home: 'الصفحة الرئيسية للين', menu: 'القائمة', primary: 'التنقل الرئيسي', footer: 'روابط التذييل' },
    cta: {
      soon: 'قريبًا',
      soonLong: 'قريبًا على App Store',
      download: 'حمّله من App Store',
      beta: 'انضم للنسخة التجريبية',
    },
    hero: {
      eyebrow: 'يوميات طعام للآيفون',
      title: 'وجباتك،<br><em>نفهمها بكل عناية.</em>',
      lede: 'قل للين وش أكلت — بالعربي، بالإنجليزي، أو بخلطتك الخاصة — ويتحوّل كلامك إلى صفحة جميلة في دفترك. بدون نماذج، بدون بحث، وبدون أحكام.',
      secondary: 'شوف كيف يشتغل',
      notes: ['بدون حساب', 'يشتغل بدون إنترنت', 'عربي و English'],
      demoLabel: 'عرض لتطبيق لين: وجبة مكتوبة بجملة وحدة تتحول إلى بطاقة محفوظة ومفصّلة.',
    },
    app: {
      today: 'اليوم',
      of: 'من',
      kcal: 'سعرة',
      left: 'باقي',
      goal: 2200,
      placeholder: 'وش أكلت؟',
      photo: 'صورة',
      speak: 'تحدّث',
      saved: 'تم الحفظ',
      undo: 'تراجع',
      edit: 'تعديل',
      perServing: 'لكل حصة:',
      servings: (n) => (n === 1 ? 'حصة واحدة' : n === 2 ? 'عدد الحصص: ٢' : `عدد الحصص: ${n}`),
      greeting: 'قل لي شي واحد أكلته اليوم — بأي كلمات («كرك وتوست»، «كبسة دجاج») وأنا أتكفّل بالباقي.',
      scenes: [
        { text: 'بيضتين وتوست', items: [scene('eggs', 2), scene('toast', 1)],
          reply: 'تمام. بيض مخفوق وتوست بالزبدة — ٤٨٠ سعرة، انسجلت. صرت على ٤٨٠، وباقي لك ١٬٧٢٠.' },
        { text: 'كبسة دجاج وكرك', items: [scene('kabsa', 1), scene('milkTea', 1)],
          reply: 'كبسة وكرك — ٧٢٠ سعرة، انسجلت. صرت على ١٬٢٠٠ اليوم، وباقي لك ١٬٠٠٠.' },
        { text: 'سبانش لاتيه', items: [scene('spanish', 1)],
          reply: 'السبانش لاتيه؟ ٢٧٠ سعرة وحوالي ١٥٠ ملغ كافيين. بس أنا ما أحكم عليك.' },
      ],
    },
    ways: {
      kicker: 'طريقة الاستخدام',
      title: 'جملة وحدة<br><em>تكفي.</em>',
      lede: 'سجّل أكلك مثل ما تحكيه لصديق. لين يتكفّل بالكميات والأرقام وترتيب الصفحة.',
      type: { title: 'اكتبها', body: '«بيضتين وتوست». خلاص — مفصّلة ومحسوبة ومحفوظة في ثانية.', demo: 'كبسة دجاج وكرك' },
      say: { title: 'قلها', body: 'اضغط المايك وتكلّم. كلامك يظهر قدامك قبل ما ينرسل أي شي.', demo: ['بيضتين', 'وتوست', 'وكوب', 'كرك'], listening: 'أسمعك…' },
      snap: { title: 'صوّرها', body: 'صوّر صحنك، ولين يقرأ اللي فيه.', fine: 'قراءة الصور تستخدم المعالجة السحابية الاختيارية — وبإذنك فقط.', reading: 'نقرأ صحنك…' },
    },
    food: {
      kicker: 'يعرف أكلك',
      title: 'كبسة في البيت. كرك آخر الليل.<br><em>لين يعرفها كلها.</em>',
      lede: 'لين جاهز بأطباق المنطقة ومشروبات الكافيهات وقوائم المطاعم — ويفهم العربي والإنجليزي، حتى لو خلطتهم في نفس الجملة.',
      marqueeA, marqueeB,
      mixed: { text: 'chicken kabsa مع كرك', caption: 'اخلط اللغات براحتك. لين يلحقك.', items: ['kabsa', 'milkTea'] },
    },
    correct: {
      kicker: 'صادق بطبعه',
      title: 'صحّحها مثل ما<br><em>تقولها.</em>',
      lede: '«خلها ثنتين». «ما أكلت البطاطس». التصحيح مجرد كلام — والتراجع دايمًا على بُعد ضغطة.',
      fix: 'خلها ثنتين',
      reply: 'تم — صارت شريحتين.',
      honestTitle: 'أرقام صادقة',
      honestBody: 'إذا كان الرقم تقديريًا، لين يقولها — «~٦٥٠» — وتعديل الكمية على بُعد ضغطة. لا دقة مزيفة، أبدًا.',
      estimate: 'تقديري · اضغط للتعديل',
    },
    ledger: {
      kicker: 'الدفتر',
      title: 'دفتر أكلك،<br><em>كأنه مجلة.</em>',
      lede: 'قرّب بأصبعين ويتحوّل كل أكلك إلى صفحات — كل صحن بأسلوب لين الدافئ، يوم بيوم وأسبوع بأسبوع.',
      points: ['أسبوعك بنظرة وحدة', 'ابحث بالأكلة أو الوجبة أو اليوم', 'شارك أي بطاقة كصورة مصممة'],
      mock: {
        title: 'الدفتر',
        search: 'أكلة، وجبة، أو تاريخ',
        stats: '٥ أيام · ١٦ صحن',
        week: 'أسبوعك',
        days: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
        summary: '٥ أيام مسجّلة · ١١ أكلة مختلفة',
        top: [{ key: 'karak', times: '٣ مرات' }, { key: 'kabsa', times: 'مرتين' }, { key: 'dates', times: 'مرتين' }],
        today: 'اليوم',
        todayKcal: '١٬٠٣٥ سعرة',
        plates: [
          { key: 'eggs', meal: 'فطور' }, { key: 'karak', meal: 'فطور' },
          { key: 'kabsa', meal: 'غداء' }, { key: 'dates', meal: 'سناك' },
        ],
        yesterday: 'أمس',
        yesterdayKcal: '١٬٦٧٠ سعرة',
        plates2: [{ key: 'shakshuka', meal: 'فطور' }, { key: 'spanish', meal: 'سناك' }, { key: 'mandi', meal: 'عشاء' }, { key: 'kunafa', meal: 'حلا' }],
      },
    },
    gentle: {
      kicker: 'وإذا تبيها ألطف',
      title: 'الأرقام، بس إذا<br><em>تبيها.</em>',
      lede: 'قل «اخف السعرات» وتختفي الأرقام من الصفحات — ودفترك يكمل بالأكل والبروتين بدل الحسبة. قل «اظهر السعرات» وترجع.',
      hide: 'اخف السعرات',
      show: 'اظهر السعرات',
      try: 'اضغط وجرّبها',
      promise: 'لين ما يحكم عليك، ولا يوبّخك، ولا يحمرّ.',
      day: 'الخميس',
      rows: [
        { key: 'karak', meal: 'الصبح', protein: '٣ غ بروتين' },
        { key: 'kabsa', meal: 'الغداء', protein: '٣٨ غ بروتين' },
        { key: 'dates', meal: 'العصر', protein: '١ غ بروتين' },
      ],
      totalKcal: '٨٥٣ سعرة',
      totalGentle: '٣ صحون · ٤٢ غ بروتين',
    },
    smart: {
      kicker: 'ذكي بهدوء',
      title: 'نعتني بالتفاصيل<br><em>عنك.</em>',
      items: [
        { icon: 'ask', title: 'اسأل دفترك', body: '«كم كافيين اليوم؟» الإجابة تجيك ومعها إيصالاتها — الوجبات اللي ورا كل رقم.', q: 'كم كافيين اليوم؟', a: '٢٤٠ ملغ — كرك، وسبانش لاتيه، وقهوة عربية.' },
        { icon: 'drop', title: 'أبعد من السعرات', body: 'الكافيين بالملغ. السكر والصوديوم والألياف من الملصقات الحقيقية. والبروتين والكارب والدهون في كل بطاقة.' },
        { icon: 'repeat', title: 'وجباتك المعتادة', body: 'وجباتك المحفوظة ترجع بضغطة — فطورك المعتاد سطر واحد، مو بحث.' },
        { icon: 'week', title: 'خلاصة أسبوعك', body: 'نظرة مصوّرة على أسبوعك، تقرأها كأنها رسالة من صديق، مو تقرير مدرسي.' },
        { icon: 'heart', title: 'صحة آبل', body: 'وجباتك توصل لتطبيق صحة آبل، ونشاطك يظهر في حسبة يومك.' },
        { icon: 'widget', title: 'ودجت بثيمك', body: 'دفتر اليوم على شاشتك الرئيسية، بنفس ثيم التطبيق.' },
      ],
    },
    themes: {
      title: 'خلّه على ذوقك.',
      lede: 'أربع ثيمات للدفتر، ولكل ثيم أيقونة تناسبه. جرّب واحد — والصفحة بتلحقك.',
      names: { matcha: 'ماتشا', lilac: 'ليلك', peach: 'خوخي', ocean: 'محيط' },
      label: 'اختر ثيم',
    },
    privacy: {
      kicker: 'خصوصيتك أولًا',
      title: 'دفترك يعيش<br><em>على جوالك.</em>',
      points: [
        { title: 'بدون حساب، بدون تسجيل', body: 'افتح التطبيق وابدأ. لين ما يطلب اسمك ولا إيميلك ولا رقمك.' },
        { title: 'على الجهاز افتراضيًا', body: 'على الآيفونات المدعومة، يفهم نموذج آبل على الجهاز وجباتك. كلامك يظل في جوالك.' },
        { title: 'يشتغل بدون إنترنت', body: 'دفترك ومعرفة لين المدمجة بالأكل تشتغل بدون اتصال.' },
        { title: 'السحابة باختيارك', body: 'تبي فهمًا سحابيًا أذكى؟ لين يستأذنك أول، ويوضّح وش ينرسل، وترجع متى ما بغيت.' },
        { title: 'بدون إعلانات، بدون تتبع', body: 'ما فيه أدوات إعلانات ولا تحليلات. أكلك لك.' },
      ],
      link: 'اقرأ سياسة الخصوصية',
    },
    story: {
      kicker: 'ليش «لين»؟',
      title: 'من اللين —<br><em>بلا ذنب ولا أحكام.</em>',
      body: 'الشعار يجمع حرف L اللاتيني مع حرف ل العربي. والاسم من اللين: دفتر بلا شعور بالذنب وبلا محاضرات — بس سجل هادئ وجميل لأكلك، باللغة اللي تفكر فيها.',
      alt: 'شعار لين: حرف مخطوط يُقرأ L و ل في نفس الوقت',
    },
    faq: {
      kicker: 'الأسئلة',
      title: 'أسئلتك،<br><em>وإجاباتها.</em>',
      items: [
        { q: 'متى أقدر أحمّل لين؟', a: 'لين حاليًا في مرحلة تجريبية، وقريبًا على App Store للآيفون.' },
        { q: 'هل لين مجاني؟', a: 'نعم — التسجيل في دفتر لين مجاني. واشتراك «لين برو» الاختياري يضيف فهمًا سحابيًا أذكى، وتفاصيله تظهر لك بوضوح داخل التطبيق قبل ما تشترك.' },
        { q: 'أحتاج حساب؟', a: 'لا. بدون تسجيل وبدون دخول. دفترك محفوظ على جوالك، مع نسخ احتياطي اختياري على iCloud الخاص فيك.' },
        { q: 'هل يفهم العربي فعلًا؟', a: 'أكيد. لين متوفر كاملًا بالعربي والإنجليزي، وتقدر تسجّل بأي لغة — أو بالاثنتين في جملة وحدة.' },
        { q: 'أي آيفون يدعم؟', a: 'لين يشتغل على الآيفونات بنظام iOS 18.1 أو أحدث. وعلى الآيفونات اللي فيها Apple Intelligence، يستخدم نموذج آبل على الجهاز لفهم أعمق؛ وعلى غيرها، تتكفّل المطابقة المدمجة بالمهمة.' },
        { q: 'هل لين استشارة طبية أو غذائية؟', a: 'لا. لين دفتر يوميات، مو استشارة طبية. الأرقام تقديرية ولين يوضّح لك ذلك. لأسئلة التغذية الطبية، استشر مختصًا.' },
      ],
    },
    final: {
      title: 'الصفحة لسّا<br><em>فاضية اليوم.</em>',
      lede: 'لين قريبًا على App Store. وأول صفحة في دفترك تحتاج جملة وحدة بس.',
      ledeLive: 'أول صفحة في دفترك تحتاج جملة وحدة بس.',
    },
    footer: {
      tagline: 'وجباتك، نفهمها بكل عناية.',
      privacy: 'الخصوصية',
      terms: 'الشروط',
      contact: 'تواصل معنا',
      legal: 'لين دفتر يوميات، مو استشارة طبية.',
      trademarks: 'Apple وiPhone وApple Health وApple Intelligence وiCloud وApp Store علامات تجارية لشركة Apple Inc.',
      madeIn: 'مصنوع بعناية للكبسة والكرك وكل شي بينهم.',
    },
    notFound: {
      title: 'هذي الصفحة مو في الدفتر.',
      body: 'يمكن الرابط قديم، أو الصفحة انتقلت. خلنا نرجعك للبداية.',
      home: 'ارجع للين',
    },
    legalNav: { back: 'ارجع للين', updated: 'آخر تحديث' },
  },
};
